# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cars_info_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from controllers import controller_parking_lot

class Ui_cars_info_window(object):
    def setupUi(self, cars_info_window):
        cars_info_window.setObjectName("cars_info_window")
        cars_info_window.resize(772, 286)
        self.cars_info_section = QtWidgets.QGroupBox(cars_info_window)
        self.cars_info_section.setGeometry(QtCore.QRect(10, 20, 741, 241))
        self.cars_info_section.setObjectName("cars_info_section")
        self.cars_info_table = QtWidgets.QTableWidget(self.cars_info_section)
        self.cars_info_table.setGeometry(QtCore.QRect(20, 30, 701, 191))
        self.cars_info_table.setObjectName("cars_info_table")
        self.cars_info_table.setColumnCount(4)

        amount_of_cars = controller_parking_lot.amount_of_cars()

        self.cars_info_table.setRowCount(amount_of_cars)
        item = QtWidgets.QTableWidgetItem()
        self.cars_info_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cars_info_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cars_info_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cars_info_table.setHorizontalHeaderItem(3, item)

        self.retranslateUi(cars_info_window)
        QtCore.QMetaObject.connectSlotsByName(cars_info_window)

    def retranslateUi(self, cars_info_window):
        _translate = QtCore.QCoreApplication.translate
        cars_info_window.setWindowTitle(_translate("cars_info_window", "Información de los carros"))
        self.cars_info_section.setTitle(_translate("cars_info_window", "Información de los carros"))
        item = self.cars_info_table.horizontalHeaderItem(0)
        item.setText(_translate("cars_info_window", "Marca del carro"))
        item = self.cars_info_table.horizontalHeaderItem(1)
        item.setText(_translate("cars_info_window", "Tipo de carro"))
        item = self.cars_info_table.horizontalHeaderItem(2)
        item.setText(_translate("cars_info_window", "Placa"))
        item = self.cars_info_table.horizontalHeaderItem(3)
        item.setText(_translate("cars_info_window", "Fecha de ingreso"))

    def show_message(self, message, type_message):
        msg = QMessageBox()
        msg.setText(message)
        msg.setIcon(type_message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def load_data(self, car, position):
        if car is None:
            self.show_message("El carro no pudo ser encontrado(a), intente de nuevo.", QMessageBox.Critical)
        else:
            self.cars_info_table.setItem(position, 0, QtWidgets.QTableWidgetItem(str(car.car_brand)))
            self.cars_info_table.setItem(position, 1, QtWidgets.QTableWidgetItem(str(car.car_type)))
            self.cars_info_table.setItem(position, 2, QtWidgets.QTableWidgetItem(str(car.car_id)))
            self.cars_info_table.setItem(position, 3, QtWidgets.QTableWidgetItem(str(car.date_of_access)))

    def load_cars(self):
        position = 0
        amount_of_cars = controller_parking_lot.amount_of_cars()
        while position != amount_of_cars:
            for car in controller_parking_lot.parking_lot.cars:
                self.load_data(car, position)
                position += 1
