# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_car.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_car_delete_form(object):
    def setupUi(self, car_delete_form):
        car_delete_form.setObjectName("car_delete_form")
        car_delete_form.resize(335, 107)
        self.instructions_delete_car = QtWidgets.QLabel(car_delete_form)
        self.instructions_delete_car.setGeometry(QtCore.QRect(10, 10, 211, 16))
        self.instructions_delete_car.setObjectName("instructions_delete_car")
        self.text_id = QtWidgets.QLabel(car_delete_form)
        self.text_id.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.text_id.setObjectName("text_id")
        self.id = QtWidgets.QLineEdit(car_delete_form)
        self.id.setGeometry(QtCore.QRect(50, 40, 241, 20))
        self.id.setObjectName("id")
        self.button_delete_car = QtWidgets.QPushButton(car_delete_form)
        self.button_delete_car.setGeometry(QtCore.QRect(250, 80, 71, 23))
        self.button_delete_car.setObjectName("button_delete_car")

        self.retranslateUi(car_delete_form)
        QtCore.QMetaObject.connectSlotsByName(car_delete_form)

    def retranslateUi(self, car_delete_form):
        _translate = QtCore.QCoreApplication.translate
        car_delete_form.setWindowTitle(_translate("car_delete_form", "Eliminar carro"))
        self.instructions_delete_car.setText(_translate("car_delete_form", "Por favor ingrela placa del carro a eliminar:"))
        self.text_id.setText(_translate("car_delete_form", "Placa"))
        self.button_delete_car.setText(_translate("car_delete_form", "Eliminar"))
