# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fees_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fees_info(object):
    def setupUi(self, fees_info):
        fees_info.setObjectName("fees_info")
        fees_info.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(fees_info)
        self.centralwidget.setObjectName("centralwidget")
        self.img_parking_lot_fees = QtWidgets.QLabel(self.centralwidget)
        self.img_parking_lot_fees.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.img_parking_lot_fees.setText("")
        self.img_parking_lot_fees.setPixmap(QtGui.QPixmap("fee.jpg"))
        self.img_parking_lot_fees.setScaledContents(True)
        self.img_parking_lot_fees.setObjectName("img_parking_lot_fees")
        fees_info.setCentralWidget(self.centralwidget)

        self.retranslateUi(fees_info)
        QtCore.QMetaObject.connectSlotsByName(fees_info)

    def retranslateUi(self, fees_info):
        _translate = QtCore.QCoreApplication.translate
        fees_info.setWindowTitle(_translate("fees_info", "Tarifas del parqueadero"))
