# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parking_lot_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_parking_lot_form(object):
    def setupUi(self, add_parking_lot_form):
        add_parking_lot_form.setObjectName("add_parking_lot_form")
        add_parking_lot_form.resize(397, 149)
        self.parking_lot_info = QtWidgets.QGroupBox(add_parking_lot_form)
        self.parking_lot_info.setGeometry(QtCore.QRect(10, 10, 381, 131))
        self.parking_lot_info.setObjectName("parking_lot_info")
        self.text_hospital_name = QtWidgets.QLabel(self.parking_lot_info)
        self.text_hospital_name.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.text_hospital_name.setObjectName("text_hospital_name")
        self.parking_lot_name = QtWidgets.QLineEdit(self.parking_lot_info)
        self.parking_lot_name.setGeometry(QtCore.QRect(140, 60, 211, 20))
        self.parking_lot_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.parking_lot_name.setText("")
        self.parking_lot_name.setObjectName("parking_lot_name")
        self.instructions_add_parking_lot = QtWidgets.QLabel(self.parking_lot_info)
        self.instructions_add_parking_lot.setGeometry(QtCore.QRect(10, 20, 331, 16))
        self.instructions_add_parking_lot.setObjectName("instructions_add_parking_lot")
        self.button_add_parking_lot = QtWidgets.QPushButton(self.parking_lot_info)
        self.button_add_parking_lot.setGeometry(QtCore.QRect(264, 100, 111, 23))
        self.button_add_parking_lot.setObjectName("button_add_parking_lot")

        self.retranslateUi(add_parking_lot_form)
        QtCore.QMetaObject.connectSlotsByName(add_parking_lot_form)

    def retranslateUi(self, add_parking_lot_form):
        _translate = QtCore.QCoreApplication.translate
        add_parking_lot_form.setWindowTitle(_translate("add_parking_lot_form", "Añadir parqueadero"))
        self.parking_lot_info.setTitle(_translate("add_parking_lot_form", "Datos del parqueadero"))
        self.text_hospital_name.setText(_translate("add_parking_lot_form", "Nombre del parqueadero"))
        self.instructions_add_parking_lot.setText(_translate("add_parking_lot_form", "Por favor ingrese el nombre del parqueadero:"))
        self.button_add_parking_lot.setText(_translate("add_parking_lot_form", "Añadir parqueadero"))
