# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_car_id.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_car_search_form(object):
    def setupUi(self, car_search_form):
        car_search_form.setObjectName("car_search_form")
        car_search_form.resize(335, 107)
        self.instructions_search_doctor = QtWidgets.QLabel(car_search_form)
        self.instructions_search_doctor.setGeometry(QtCore.QRect(10, 10, 291, 16))
        self.instructions_search_doctor.setObjectName("instructions_search_doctor")
        self.text_id = QtWidgets.QLabel(car_search_form)
        self.text_id.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.text_id.setObjectName("text_id")
        self.id = QtWidgets.QLineEdit(car_search_form)
        self.id.setGeometry(QtCore.QRect(50, 40, 241, 20))
        self.id.setObjectName("id")
        self.button_search_doctor_name = QtWidgets.QPushButton(car_search_form)
        self.button_search_doctor_name.setGeometry(QtCore.QRect(250, 80, 71, 23))
        self.button_search_doctor_name.setObjectName("button_search_doctor_name")

        self.retranslateUi(car_search_form)
        QtCore.QMetaObject.connectSlotsByName(car_search_form)

    def retranslateUi(self, car_search_form):
        _translate = QtCore.QCoreApplication.translate
        car_search_form.setWindowTitle(_translate("car_search_form", "Buscar carro por placa"))
        self.instructions_search_doctor.setText(_translate("car_search_form", "Por favor ingre la placa del carro que busca:"))
        self.text_id.setText(_translate("car_search_form", "Placa"))
        self.button_search_doctor_name.setText(_translate("car_search_form", "Buscar"))
